version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: back/Dockerfile
    ports:
      - "8005:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
  frontend:
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - PORT=3000
      - HOST="127.0.0.1"
