version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: back/Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - .env
  frontend:
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env
