version: "3.7"

services:
  backend:
    build:
      context: .
      dockerfile: back/Dockerfile
    ports:
      - "8000:8000"
  frontend:
    build:
      context: front
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
